version: "4.2"

services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "9090:9090"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
